---
- name: Converge
  hosts: all
  vars:
    promtail_scrape_configs:
      - job_name: test
        static_configs:
          - targets:
              - localhost
            labels:
              job: test
              instance: "{{ ansible_fqdn }}"
              __path__: /var/log/*log
  roles:
    - role: voidquark.promtail
